[package]
name = "embed"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
scraper = "0.19"
serde = { version = "1.0", optional = true, features = ["derive"] }

url = "2"
percent-encoding = "2"

tracing = "0.1"
